version: "3"

services:
  app:
    build: .
    container_name: iqos-iluma.rf
    restart: always
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=xn----7sbb5adgjio4a0m.xn--p1ai
      - LETSENCRYPT_HOST=xn----7sbb5adgjio4a0m.xn--p1ai
      - LETSENCRYPT_EMAIL=qwe@gmail.com
    networks:
      - web
    volumes:
      # Все сайты используют одну и ту же папку с картинками
      - /var/www/iluma-store.ru/images:/app/public/images:ro
      # - /var/www/iqos-iluma.rf/.next:/app/.next

networks:
  web:
    external: true
